### PR TITLE
Fixing issue with UTF-8 conversion in Python3 for GCS uploads

### PR DESCRIPTION
**Pull request by bucklander**
##### SUMMARY
Fixing issue with UTF-8 conversion in Python3 for GCS uploads (https://github.com/ansible-collections/google.cloud/issues/266)

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
gcp_storage_object

##### ADDITIONAL INFORMATION
This bug can be resolved by simply changing gcp_storage_object.py#L254 from ...

`with open(src, "r") as file_obj:` to `with open(src, "rb") as file_obj:`

Hence, this PR. This small change ensures there's no decoding attempt (or subsequent error) by forcing the file to be read as binary via the `open` func.

This approach appears similar to `download_file`'s use of the open func at gcp_storage_object.py#L243, where it specifically is configured with the b (binary) mode specifier. Not only does this resolve the issue with uploading binary files, but the change doesn't appear to harm text uploads. Unsure though if this is a safe strategy overall and should be probably be reviewed carefully by Google Ansible module maintainers.

```
$ ansible-playbook --connection=local --inventory localhost, upload-text-file.yml -e ansible_python_interpreter=`which python2`


PLAY [Upload a file to GCS using gcp_storage_object module] ****************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Upload Latest Backup(s) to GCS Bucket] *******************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

```
$ ansible-playbook --connection=local --inventory localhost, upload-text-file.yml -e ansible_python_interpreter=`which python3`


PLAY [Upload a file to GCS using gcp_storage_object module] ****************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Upload Latest Backup(s) to GCS Bucket] *******************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

```
$ ansible-playbook --connection=local --inventory localhost, upload-bin-file.yml -e ansible_python_interpreter=`which python2`

PLAY [Upload a binary file to Google Cloud Storage bucket using gcp_storage_object module] *********************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Upload Latest Backup(s) to GCS Bucket] *******************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

```
$ ansible-playbook --connection=local --inventory localhost, upload-bin-file.yml -e ansible_python_interpreter=`which python3`

PLAY [Upload a binary file to Google Cloud Storage bucket using gcp_storage_object module] *********************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Upload Latest Backup(s) to GCS Bucket] *******************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### CODE REVIEW

**Comment by bucklander** [comment]
Additionally, according to [this Google Cloud doc](https://cloud.google.com/storage/docs/uploading-objects#rest-upload-objects), the preference appears to be to read and use the given file in binary exactly as given (I.e. no conversion). It would seem that this supports the change here.

**Comment by bucklander** [comment]
giphy

**Comment by mxdlx** [comment]
I think I spent two hours until finding this. Good old Ansible.

**Comment by bucklander** [comment]
I've since given up here, doesn't seem to me that Google Cloud is investing much in their Ansible module collection. If anyone else runs across this issue, I recommend interacting with Google's Cloud APIs as much as possible simply using Ansible's `URI` module instead.

Example:
```
- name: Upload Tarball to GCS Bucket
        uri:
          url: https://storage.googleapis.com/upload/storage/v1/b/{{ gcs_bucket_name }}/o?uploadType=media&name={{ filename }}.tar
          validate_certs: false
          timeout: 720
          method: POST
          src: {{ filename }}.tar
          remote_src: yes
          return_content: yes
          headers:
            Authorization: Bearer {{ gcs_token_resp.json.access_token }}
            Content-Type: application/x-tar
        ignore_errors: yes
```

**Comment by dperezro** [comment]
Hello! When will this be merged?

**Comment by dperezro** [comment]
7940f72cb3c1cb274c191214c1e1dee4

**Comment by levonet** [comment]
Maybe there is some alternative to google.cloud collection?

**Comment by dperezro** [comment]
@levonet there is... but it's a shame they do not fix this and abandon it.

**Comment by dalbani** [comment]
@dperezro
What is the alternative that you known of?

**Comment by dperezro** [comment]
> @dperezro
> What is the alternative that you known of?

Google's Cloud APIs, using gcloud commands (although it's interactive so you need to run gcloud login first) or make this correction locally (the PR change) :-\

**Comment by ikauzak** [comment]
Still facing the same issue. Hope someone fixes this asap D:

**Comment by bucklander** [comment]
hail marry attempt for merge - @rambleraptor

**Comment by levonet** [comment]
I finally realized it was a conspiracy between google and ansible. The purpose of the conspiracy is to migrate everyone to k8s, helm, and terraform. It happened to me :/

**Comment by mxdlx** [comment]
@rambleraptor mentioning you since you seem to be main contributor. Any chance this can be merged? Pretty please?

**Comment by nkvojvodic** [comment]
I find GCP's lack of interest in merging simple, badly needed fixes...disturbing.

@rmoriar1 
Any chance of getting this merged?

**Comment by mxdlx** [comment]
Thanks for merging that, I noticed that the last release for this collection was on February 2020. I spent all day doing a manual fix to get this specific commit as a requirement in AWX, turns out that AWX with Ansible 2.9 can't use `requirements.yml` with a git version.
So, here's hoping for a 1.0.3 release.
Thanks again, I first noticed this issue on 09/10/2021.

**Comment by jessequinn** [comment]
Should help someone

`requirements.yml`

```
collections:
  - name: git+https://github.com/ansible-collections/google.cloud.git
```

**Pull request merged**
